In [1]:
import pandas as pd
import numpy as np

In [2]:
PerformanceColumnNames = (
    "LOAN_ID", "Monthly.Rpt.Prd", "Servicer.Name", 
    "LAST_RT", "LAST_UPB", "Loan.Age", "Months.To.Legal.Mat", 
    "Adj.Month.To.Mat", "Maturity.Date", "MSA", 
    "Delq.Status", "MOD_FLAG", "Zero.Bal.Code", 
    "ZB_DTE", "LPI_DTE", "FCC_DTE","DISP_DT", 
    "FCC_COST", "PP_COST", "AR_COST", "IE_COST", 
    "TAX_COST", "NS_PROCS","CE_PROCS", "RMW_PROCS", 
    "O_PROCS", "NON_INT_UPB", "PRIN_FORG_UPB_FHFA", 
    "REPCH_FLAG", "PRIN_FORG_UPB_OTH", "TRANSFER_FLG"
)

In [3]:
performance_df = pd.read_csv(r'C:\Users\alpal\Desktop\FE-690\Mortgage Data\Performance_2010Q1.txt',
                    names=PerformanceColumnNames,
                    header=None,
                    sep="|"
)

C:\Users\alpal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
performance_df.head()

,LOAN_ID,Monthly.Rpt.Prd,Servicer.Name,LAST_RT,LAST_UPB,Loan.Age,Months.To.Legal.Mat,Adj.Month.To.Mat,Maturity.Date,MSA,...,TAX_COST,NS_PROCS,CE_PROCS,RMW_PROCS,O_PROCS,NON_INT_UPB,PRIN_FORG_UPB_FHFA,REPCH_FLAG,PRIN_FORG_UPB_OTH,TRANSFER_FLG
0,100010079393,02/01/2010,"WELLS FARGO BANK, N.A.",4.875,NaN,0,360,360.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,100010079393,03/01/2010,NaN,4.875,NaN,1,359,358.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,100010079393,04/01/2010,NaN,4.875,NaN,2,358,358.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,100010079393,05/01/2010,NaN,4.875,NaN,3,357,357.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,100010079393,06/01/2010,NaN,4.875,NaN,4,356,355.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

__Still experiencing memory errors__

In [5]:
performance_df['Monthly.Rpt.Prd'] = pd.to_datetime(performance_df['Monthly.Rpt.Prd'])

KeyboardInterrupt:

In [ ]:
performance_train = performance_df[performance_df['Monthly.Rpt.Prd'] < '2015/01/01']
performance_test = performance_df[performance_df['Monthly.Rpt.Prd'] >= '2015/01/01']